name: ci
on: [push]
jobs:
  lint-and-build:
    runs-on: ubuntu-18.04
    container:
      image: node:12-alpine
      env:
        NODE_ENV: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Install dependencies
        run: yarn install
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
